- hosts: all
  tasks:
  - name: Fetch package update
    become: yes
    command: apt update
  - name: Refresh package lastet
    become: yes
    command: apt upgrade -y
  - name: Get EC2 instance ID
    command: curl 169.254.169.254/latest/meta-data/instance-id/
    register: ec2_instance_id
  - name: Associate a security group
    become: yes
    command: aws ec2 modify-instance-attribute --instance-id "{{ ec2_instance_id.stdout }}" --groups "{{ security-group-id }}"
